version: "3.8"

services:
  boot-otel-tempo-provider1:
    image: "mnadeem/boot-otel-tempo-provider1:0.0.1-SNAPSHOT"
    container_name: boot-otel-tempo-provider1
    networks:
      - grafana_default
    ports:
      - "8070:8090"
    environment:
      PROVIDER1_DB_URL: jdbc:postgresql://provider1-db:5432/provider1
      PROVIDER1_DB_USER: postgres
      PROVIDER1_DB_PASS: postgrespassword
    volumes:
      - /home/ec2-user/grafana/promtail:/app/logs
    external_links:
      - grafana_tempo_1:tempo
    depends_on:
      - provider1-db
  provider1-db:
    image: postgres
    container_name: provider1-db
    networks:
      - grafana_default
    restart: always
    environment:
      - POSTGRES_DB=provider1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./../boot-otel-tempo-provider1/db/data:/var/lib/postgresql
      - ./../boot-otel-tempo-provider1/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  boot-otel-tempo-api:
    image: "mnadeem/boot-otel-tempo-api:0.0.1-SNAPSHOT"
    container_name: boot-otel-tempo-api
    networks:
      - grafana_default
    ports:
      - "8071:8080"
    environment:
      PROVIDER1_URL_BASE: "http://boot-otel-tempo-provider1:8090"
    volumes:
      - /home/ec2-user/grafana/promtail:/app/logs
    depends_on:
      - boot-otel-tempo-provider1
networks:
  grafana_default:
    external: true