version: "3.8"

services:
  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317"        # OTLP gRPC receiver
    networks:
      - xs-bridge
  boot-otel-tempo-provider1-opentelemetry-skywalking:
    image: "mnadeem/boot-otel-tempo-provider1-opentelemetry-skywalking:0.0.1-SNAPSHOT"
    container_name: boot-otel-tempo-provider1-opentelemetry-skywalking
    networks:
      - xs-bridge
    ports:
      - "8092:8090"
    environment:
      PROVIDER1_DB_URL: jdbc:postgresql://provider1-db:5432/provider1
      PROVIDER1_DB_USER: postgres
      PROVIDER1_DB_PASS: postgrespassword
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    volumes:
      - ./../data/logs:/app/logs
    external_links:
      - provider1-db:provider1-db
  boot-otel-tempo-api-opentelemetry-skywalking:
    image: "mnadeem/boot-otel-tempo-api-opentelemetry-skywalking:0.0.1-SNAPSHOT"
    container_name: boot-otel-tempo-api-opentelemetry-skywalking
    networks:
      - xs-bridge
    ports:
      - "8072:8080"
    environment:
      PROVIDER1_URL_BASE: "http://boot-otel-tempo-provider1:8090"
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    volumes:
      - ./../data/logs:/app/logs
    depends_on:
      - boot-otel-tempo-provider1-opentelemetry-skywalking
networks:
  xs-bridge:
    external: true