receivers:
  otlp:
    protocols:
      grpc:
#  skywalking:
#    protocols:
#      grpc:
#        endpoint: oap:11800

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  skywalking:
    endpoint: oap:11800
    tls:
      insecure: true
    num_streams: 5
  #  skywalking/2:
  #    endpoint: 192.168.100.10:11800
  #    compression: "gzip"
  #    tls:
  #      cert_file: file.cert
  #      key_file: file.key
  #    timeout: 10s

  #  prometheus:
  #    endpoint: "0.0.0.0:8889"
  #    const_labels:
  #      label1: value1

  logging:

#  zipkin:
#    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
#    format: proto
#
#  jaeger:
#    endpoint: jaeger-all-in-one:14250
#    tls:
#      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

#extensions:
#  health_check:
#  pprof:
#    endpoint: :1888
#  zpages:
#    endpoint: :55679

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging,jaeger ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ skywalking ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ skywalking ]