receivers:
  skywalking:
    protocols:
      grpc:
        endpoint: 0.0.0.0:11800
      http:
        endpoint: 0.0.0.0:12800

exporters:
#  skywalking:
#    endpoint: 192.168.100.10:11800
#    tls:
#      insecure: true
#    num_streams: 5
#  skywalking/2:
#    endpoint: 192.168.100.10:11800
#    compression: "gzip"
#    tls:
#      cert_file: file.cert
#      key_file: file.key
#    timeout: 10s

#  prometheus:
#    endpoint: "0.0.0.0:8889"
#    const_labels:
#      label1: value1

  logging:

#  zipkin:
#    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
#    format: proto
#
#  jaeger:
#    endpoint: jaeger-all-in-one:14250
#    tls:
#      insecure: true

processors:
  batch:

#extensions:
#  health_check:
#  pprof:
#    endpoint: :1888
#  zpages:
#    endpoint: :55679

service:
  pipelines:
    traces:
      receivers: [skywalking]
#      processors: [batch]
#      exporters: [logging, zipkin, jaeger]
      exporters: [logging]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [logging, prometheus]
#      exporters: [skywalking]