receivers:
  skywalking:
    protocols:
      grpc:
        endpoint: 192.168.100.10:11800
      http:
        endpoint: 192.168.100.10:12800

exporters:
#  prometheus:
#    endpoint: "0.0.0.0:8889"
#    const_labels:
#      label1: value1

  logging:

#  zipkin:
#    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
#    format: proto
#
#  jaeger:
#    endpoint: jaeger-all-in-one:14250
#    tls:
#      insecure: true

processors:
  batch:

#extensions:
#  health_check:
#  pprof:
#    endpoint: :1888
#  zpages:
#    endpoint: :55679

service:
  pipelines:
    traces:
      receivers: [skywalking]
#      processors: [batch]
#      exporters: [logging, zipkin, jaeger]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [logging, prometheus]