receivers:
  otlp:
    protocols:
      grpc:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'vm-monitoring' # make sure to use this in the vm.yaml to filter only VM metrics
          scrape_interval: 10s
          static_configs:
            - targets: [ 'node-exporter:9100' ]
  skywalking/defaults:
    protocols:
      grpc:
  skywalking:
    protocols:
      grpc:
        endpoint: "oap:11800"

exporters:
  opencensus:
    endpoint: "oap:11800" # The OAP Server address
    tls:
      insecure: true
  skywalking:
    endpoint: "oap:11800"
    tls:
      insecure: true
  logging:
    logLevel: info
processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp, skywalking ]
#      processors: [ batch ]
      exporters: [ logging,opencensus ]
    logs:
      receivers: [ otlp ]
#      processors: [ batch ]
      exporters: [ skywalking ,logging ]
    metrics:
      receivers: [ otlp,prometheus ]
#      processors: [ batch ]
      exporters: [ skywalking,opencensus,logging ]